---
  - name: Install squid
    apt: >
      name=squid
      state=latest
  - name: Configure squid
    template: >
      src=squid.conf.j2
      dest=/etc/squid/squid.conf
      owner=root
      group=root
      mode=0644
    notify: restart squid
